### ISSUE TITLE
update machine returns internal server error 

### ISSUE THREAD

**Issue by ahsayde** [openvcloud/openvcloud#43] opened 2017-10-05 16:03 UTC
### API
```
 /cloudapi/machines/update
```

### code
```
/opt/code/github/openvcloud/openvcloud/actors/cloudapi/cloudapi__machines/methodclass/cloudapi_machines.py
```

### backtrace
```
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/portal9/JumpScale9Portal/portal/PortalRest.py", line 241, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/cloudbroker/actorlib/authenticator.py", line 133, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/github/openvcloud/openvcloud/actors/cloudapi/cloudapi__machines/methodclass/cloudapi_machines.py", line 725, in update
    self.cb.machine.assertName(machine.cloudspaceId, name)
AttributeError: 'VMachine' object has no attribute 'cloudspaceId'


```

**Comment by rkhamis** [comment] 2017-10-17 11:49
duplicate of #51

**Closed as completed by rkhamis** 2017-10-17 11:49 UTC
Labels: type_bug
